### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Hashiguchi0828** [Hashiguchi0828/protospace-38564#1]
# URL
https://protospace-38564.herokuapp.com/

**Comment by yusuketono** [comment]
@Hashiguchi0828 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
##### コメント機能
- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
自身の投稿に空のコメントをすると、エラー画面に遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Hashiguchi0828** [comment]
修正しました

**Comment by yusuketono** [comment]
@Hashiguchi0828 さん、再度ご提出ありがとうございます‼︎
確認をしたところ、前回の修正点がそのままになっているようです。
デプロイが完了できていない可能性がございますので、再度ご確認をお願い致します。

[修正依頼箇所]
##### コメント機能
- [x]  **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
自身の投稿に空のコメントをすると、エラー画面に遷移してしまいます。
<img width="662" alt="スクリーンショット 2022-10-10 12 53 32" src="https://user-images.githubusercontent.com/51428519/194797123-baee1cc6-f613-4048-a807-9b3120068326.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Hashiguchi0828** [comment]
デプロイ完了しました

**Comment by soll02solglas** [comment]
@Hashiguchi0828 さんご提出ありがとうございます ！
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
